/**
 * L2 Self-Prompt Reasoning Engine
 *
 * Three operating modes (in order of preference):
 *
 * 1. Fine-tuned Ollama SLM — fastest, most accurate, runs locally.
 *    Requires: `ollama create codebase-slm -f ./Modelfile` after training.
 *
 * 2. Base Ollama model with in-context few-shot examples — no training needed.
 *    Requires: `ollama pull qwen2.5-coder:1.5b` and a few_shot_examples.json
 *    generated by `python finetunePipeline.py --in-context`.
 *    Set OLLAMA_MODEL=codebase-slm-base and FEW_SHOT_PATH=./models/few_shot_examples.json
 *
 * 3. OpenAI-compatible API fallback — works everywhere, costs per token.
 *    Automatic when Ollama is unavailable.
 *
 * Design constraints:
 * - Max 200 lines per file
 * - Max 20 lines per function
 */

import { readFileSync, existsSync } from 'fs';

export type ReasoningMode = 'diagnose' | 'repair' | 'explain' | 'dream' | 'relate';

export interface ReasoningRequest {
  mode: ReasoningMode;
  context: string;
  nodeId?: string;
  failureDescription?: string;
}

export interface ReasoningResponse {
  mode: ReasoningMode;
  output: string;
  model: string;
  durationMs: number;
  tokenCount?: number;
}

export interface SelfPromptEngineConfig {
  ollamaUrl?: string;
  ollamaModel?: string;
  fallbackToOpenAI?: boolean;
  timeoutMs?: number;
  fewShotPath?: string;       // Path to few_shot_examples.json from --in-context mode
}

const DEFAULT_CONFIG: Required<SelfPromptEngineConfig> = {
  ollamaUrl: process.env['OLLAMA_URL'] ?? 'http://localhost:11434',
  ollamaModel: process.env['OLLAMA_MODEL'] ?? 'codebase-slm',
  fallbackToOpenAI: true,
  timeoutMs: 30_000,
  fewShotPath: process.env['FEW_SHOT_PATH'] ?? ''
};

export class SelfPromptEngine {
  private readonly config: Required<SelfPromptEngineConfig>;
  private fewShotPrefix: string = '';

  constructor(config: SelfPromptEngineConfig = {}) {
    this.config = { ...DEFAULT_CONFIG, ...config };
    this.fewShotPrefix = this.loadFewShotExamples();
  }

  /**
   * Load few-shot examples from disk if a path is configured.
   * Returns an empty string if no path is set or file does not exist.
   */
  private loadFewShotExamples(): string {
    const path = this.config.fewShotPath;
    if (!path || !existsSync(path)) return '';
    try {
      const examples = JSON.parse(readFileSync(path, 'utf-8')) as Array<{
        instruction: string;
        input?: string;
        output: string;
      }>;
      const lines = ['### Codebase Examples (use these to understand the patterns):\n'];
      for (const ex of examples.slice(0, 6)) {
        lines.push(`Q: ${ex.instruction}`);
        if (ex.input?.trim()) lines.push(`Context: ${ex.input.slice(0, 200)}`);
        lines.push(`A: ${ex.output.slice(0, 300)}\n`);
      }
      return lines.join('\n');
    } catch {
      return '';
    }
  }

  /**
   * Send a reasoning request to the SLM.
   * Automatically falls back to OpenAI if Ollama is unavailable.
   */
  public async reason(req: ReasoningRequest): Promise<ReasoningResponse> {
    const prompt = this.buildPrompt(req);
    const start = Date.now();
    const ollamaAvailable = await this.checkOllama();
    if (ollamaAvailable) return this.callOllama(prompt, req.mode, start);
    if (this.config.fallbackToOpenAI) return this.callOpenAI(prompt, req.mode, start);
    throw new Error('Ollama unavailable and OpenAI fallback is disabled.');
  }

  /**
   * Build the structured prompt. Prepends few-shot examples when available.
   */
  private buildPrompt(req: ReasoningRequest): string {
    const modeInstructions: Record<ReasoningMode, string> = {
      diagnose: 'Diagnose the following failure. Output DIAGNOSIS, LOCATION, FIX, TEST, RISK.',
      repair: 'Generate a TypeScript fix for the following issue. Follow all project conventions.',
      explain: 'Explain what the following code does in plain language.',
      dream: 'Generate a hypothesis about what could be improved. Be creative but grounded.',
      relate: 'Identify all dependencies and relationships in the following code.'
    };
    const instruction = modeInstructions[req.mode];
    const context = req.failureDescription
      ? `${req.failureDescription}\n\n${req.context}`
      : req.context;
    const prefix = this.fewShotPrefix ? `${this.fewShotPrefix}\n---\n\n` : '';
    return `${prefix}### Instruction:\n${instruction}\n\n### Input:\n${context}\n\n### Response:\n`;
  }

  /**
   * Check if the Ollama instance is running and the model is loaded.
   */
  private async checkOllama(): Promise<boolean> {
    try {
      const controller = new AbortController();
      const timeout = setTimeout(() => controller.abort(), 2000);
      const res = await fetch(`${this.config.ollamaUrl}/api/tags`, {
        signal: controller.signal
      });
      clearTimeout(timeout);
      if (!res.ok) return false;
      const data = await res.json() as { models?: Array<{ name: string }> };
      return data.models?.some(m => m.name.includes(this.config.ollamaModel)) ?? false;
    } catch {
      return false;
    }
  }

  /**
   * Call the local Ollama instance with the given prompt.
   */
  private async callOllama(
    prompt: string, mode: ReasoningMode, start: number
  ): Promise<ReasoningResponse> {
    const res = await fetch(`${this.config.ollamaUrl}/api/generate`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        model: this.config.ollamaModel,
        prompt,
        stream: false,
        options: { temperature: 0.2, num_predict: 1024 }
      })
    });
    const data = await res.json() as { response: string; eval_count?: number };
    return {
      mode, output: data.response, model: this.config.ollamaModel,
      durationMs: Date.now() - start, tokenCount: data.eval_count
    };
  }

  /**
   * Fall back to the OpenAI-compatible API when Ollama is unavailable.
   */
  private async callOpenAI(
    prompt: string, mode: ReasoningMode, start: number
  ): Promise<ReasoningResponse> {
    const baseUrl = process.env['OPENAI_API_BASE'] ?? 'https://api.openai.com/v1';
    const apiKey = process.env['OPENAI_API_KEY'] ?? '';
    const res = await fetch(`${baseUrl}/chat/completions`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${apiKey}` },
      body: JSON.stringify({
        model: 'gpt-4o-mini',
        messages: [{ role: 'user', content: prompt }],
        temperature: 0.2, max_tokens: 1024
      })
    });
    const data = await res.json() as {
      choices: Array<{ message: { content: string } }>;
      usage?: { total_tokens: number };
    };
    return {
      mode, output: data.choices[0]?.message.content ?? '',
      model: 'openai-fallback', durationMs: Date.now() - start,
      tokenCount: data.usage?.total_tokens
    };
  }
}
