/**
 * scaffoldEvaluator.ts — ScaffoldEvaluator (L4.5 of the Cognitive Loop)
 *
 * Evaluates scaffold proposals generated by the SelfPromptEngine's `dream` mode
 * against live verdict quality metrics from citation-desk. Implements the
 * Ornith-1.0 self-scaffolding RL alignment: CLF's dream mode proposes scaffolds,
 * ScaffoldEvaluator scores them, and only improvements that pass the quality
 * threshold are promoted to the active scaffold.
 *
 * Architecture:
 *   SelfPromptEngine (dream) → ScaffoldProposal
 *   ScaffoldEvaluator.evaluate() → ScaffoldVerdict
 *   If verdict.approved → LoopOrchestrator.applyScaffold()
 *
 * Design constraints:
 * - Max 200 lines per file
 * - Max 20 lines per function
 * - Uses invokeMultiLLM (Kimi K2) for evaluation — no direct LLM calls
 */

import type { ReasoningResponse } from '../slm/selfPromptEngine.js';
import type { MetaAgent } from './metaAgent.js';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface ScaffoldProposal {
  /** The raw dream-mode output from SelfPromptEngine */
  dreamOutput: string;
  /** The context that triggered the dream (e.g. failing layer name) */
  triggerContext: string;
  /** Timestamp of proposal generation */
  proposedAt: string;
  /** Loop iteration number when proposed */
  iterationNumber: number;
}

export interface ScaffoldEvaluationMetrics {
  /** Average verdict confidence across recent N verdicts (0–1) */
  avgVerdictConfidence: number;
  /** Fraction of verdicts that flipped on re-analysis (lower is better) */
  flipRate: number;
  /** Fraction of citation chains with distortion score > 0.5 */
  highDistortionRate: number;
  /** Number of verdicts in the evaluation window */
  sampleSize: number;
}

export interface ScaffoldVerdict {
  proposal: ScaffoldProposal;
  approved: boolean;
  score: number;           // 0.0 – 1.0 composite quality score
  rationale: string;
  evaluatedAt: string;
  shadowMetrics?: ScaffoldEvaluationMetrics;
}

export interface ScaffoldEvaluatorConfig {
  /** Minimum composite score to approve a proposal (default: 0.65) */
  approvalThreshold?: number;
  /** URL of ttruthdesk-platform for fetching verdict metrics */
  ttruthDeskUrl?: string;
  /** Maximum proposals to hold in shadow evaluation queue */
  maxPendingProposals?: number;
  /** Kimi API URL (falls back to KIMI_API_URL env var) */
  kimiApiUrl?: string;
  /** Kimi API key (falls back to KIMI_API_KEY env var) */
  kimiApiKey?: string;
}

// ─── ScaffoldEvaluator ────────────────────────────────────────────────────────

export class ScaffoldEvaluator {
  private readonly approvalThreshold: number;
  private readonly ttruthDeskUrl: string;
  private readonly maxPendingProposals: number;
  private readonly kimiApiUrl: string;
  private readonly kimiApiKey: string;
  private readonly pendingProposals: ScaffoldProposal[] = [];
  private readonly verdictHistory: ScaffoldVerdict[] = [];

  constructor(
    private readonly meta: MetaAgent,
    config: ScaffoldEvaluatorConfig = {}
  ) {
    this.approvalThreshold = config.approvalThreshold ?? 0.65;
    this.ttruthDeskUrl =
      config.ttruthDeskUrl ??
      process.env['TTRUTHDESK_URL'] ??
      'http://localhost:3000';
    this.maxPendingProposals = config.maxPendingProposals ?? 10;
    this.kimiApiUrl =
      config.kimiApiUrl ??
      process.env['KIMI_API_URL'] ??
      'https://api.moonshot.cn/v1';
    this.kimiApiKey =
      config.kimiApiKey ?? process.env['KIMI_API_KEY'] ?? '';
  }

  // ─── Public API ─────────────────────────────────────────────────

  /**
   * Queue a dream-mode output for shadow evaluation.
   * Returns immediately — evaluation is async.
   */
  public enqueue(
    dreamResponse: ReasoningResponse,
    triggerContext: string,
    iterationNumber: number
  ): void {
    if (this.pendingProposals.length >= this.maxPendingProposals) {
      this.pendingProposals.shift(); // drop oldest
    }
    this.pendingProposals.push({
      dreamOutput: dreamResponse.output,
      triggerContext,
      proposedAt: new Date().toISOString(),
      iterationNumber,
    });
  }

  /**
   * Evaluate all pending proposals against current verdict quality metrics.
   * Returns approved proposals only. Clears the pending queue.
   */
  public async evaluatePending(): Promise<ScaffoldVerdict[]> {
    if (this.pendingProposals.length === 0) return [];
    const metrics = await this.fetchVerdictMetrics();
    const proposals = this.pendingProposals.splice(0);
    const verdicts = await Promise.all(
      proposals.map(p => this.evaluateOne(p, metrics))
    );
    this.verdictHistory.push(...verdicts);
    const approved = verdicts.filter(v => v.approved);
    if (approved.length > 0) {
      this.meta.publishEvent({
        type: 'system_capability_required',
        severity: 'info',
        message: `ScaffoldEvaluator approved ${approved.length} scaffold proposal(s)`,
        filePath: '',
        metadata: { approvedCount: approved.length, totalEvaluated: verdicts.length },
      });
    }
    return approved;
  }

  /** Return the last N scaffold verdicts for observability */
  public recentVerdicts(n = 10): ScaffoldVerdict[] {
    return this.verdictHistory.slice(-n);
  }

  // ─── Private helpers ─────────────────────────────────────────────

  private async evaluateOne(
    proposal: ScaffoldProposal,
    metrics: ScaffoldEvaluationMetrics
  ): Promise<ScaffoldVerdict> {
    const kimiScore = await this.scoreWithKimi(proposal, metrics);
    const metricScore = this.scoreFromMetrics(metrics);
    const composite = 0.6 * kimiScore.score + 0.4 * metricScore;
    const approved = composite >= this.approvalThreshold;
    return {
      proposal,
      approved,
      score: composite,
      rationale: kimiScore.rationale,
      evaluatedAt: new Date().toISOString(),
      shadowMetrics: metrics,
    };
  }

  private scoreFromMetrics(m: ScaffoldEvaluationMetrics): number {
    if (m.sampleSize === 0) return 0.5; // no data — neutral
    const confidenceScore = m.avgVerdictConfidence;
    const flipPenalty = Math.min(m.flipRate * 2, 1.0);
    const distortionPenalty = Math.min(m.highDistortionRate * 1.5, 1.0);
    return Math.max(0, confidenceScore - flipPenalty * 0.3 - distortionPenalty * 0.2);
  }

  private async scoreWithKimi(
    proposal: ScaffoldProposal,
    metrics: ScaffoldEvaluationMetrics
  ): Promise<{ score: number; rationale: string }> {
    if (!this.kimiApiKey) {
      return { score: 0.5, rationale: 'Kimi API key not configured — neutral score.' };
    }
    try {
      const prompt = this.buildKimiPrompt(proposal, metrics);
      const res = await fetch(`${this.kimiApiUrl}/chat/completions`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${this.kimiApiKey}`,
        },
        body: JSON.stringify({
          model: 'moonshot-v1-8k',
          messages: [
            {
              role: 'system',
              content:
                'You are a scaffold quality evaluator for an autonomous scientific claim verification system. ' +
                'Score scaffold proposals on a scale of 0.0 to 1.0 based on their likely impact on verdict quality. ' +
                'Respond with valid JSON only: { "score": number, "rationale": string }',
            },
            { role: 'user', content: prompt },
          ],
          temperature: 0.1,
          max_tokens: 256,
        }),
      });
      if (!res.ok) return { score: 0.5, rationale: `Kimi API error: ${res.status}` };
      const data = await res.json() as { choices: Array<{ message: { content: string } }> };
      const content = data.choices?.[0]?.message?.content ?? '{}';
      const parsed = JSON.parse(content) as { score?: number; rationale?: string };
      return {
        score: Math.max(0, Math.min(1, parsed.score ?? 0.5)),
        rationale: parsed.rationale ?? 'No rationale provided.',
      };
    } catch {
      return { score: 0.5, rationale: 'Kimi evaluation failed — neutral score.' };
    }
  }

  private buildKimiPrompt(
    proposal: ScaffoldProposal,
    metrics: ScaffoldEvaluationMetrics
  ): string {
    return [
      `Scaffold Proposal (iteration ${proposal.iterationNumber}):`,
      `Trigger: ${proposal.triggerContext}`,
      `Proposal: ${proposal.dreamOutput.slice(0, 800)}`,
      '',
      'Current System Metrics:',
      `  Average verdict confidence: ${(metrics.avgVerdictConfidence * 100).toFixed(1)}%`,
      `  Verdict flip rate: ${(metrics.flipRate * 100).toFixed(1)}%`,
      `  High-distortion citation rate: ${(metrics.highDistortionRate * 100).toFixed(1)}%`,
      `  Sample size: ${metrics.sampleSize} verdicts`,
      '',
      'Does this scaffold proposal address the root cause of the observed quality issues? ' +
      'Score 0.0 if it is irrelevant or harmful, 1.0 if it directly targets the main quality gap.',
    ].join('\n');
  }

  private async fetchVerdictMetrics(): Promise<ScaffoldEvaluationMetrics> {
    try {
      const res = await fetch(
        `${this.ttruthDeskUrl}/api/public/stats?window=50`,
        { signal: AbortSignal.timeout(5000) }
      );
      if (!res.ok) return this.emptyMetrics();
      const data = await res.json() as {
        avgConfidence?: number;
        flipRate?: number;
        highDistortionRate?: number;
        sampleSize?: number;
      };
      return {
        avgVerdictConfidence: data.avgConfidence ?? 0.5,
        flipRate: data.flipRate ?? 0,
        highDistortionRate: data.highDistortionRate ?? 0,
        sampleSize: data.sampleSize ?? 0,
      };
    } catch {
      return this.emptyMetrics();
    }
  }

  private emptyMetrics(): ScaffoldEvaluationMetrics {
    return { avgVerdictConfidence: 0.5, flipRate: 0, highDistortionRate: 0, sampleSize: 0 };
  }
}

// ─── Singleton ────────────────────────────────────────────────────────────────
// Note: ScaffoldEvaluator requires a MetaAgent instance — the singleton is
// created lazily in loopOrchestrator.ts where the MetaAgent is available.
// This export is a factory helper for convenience.
export function createScaffoldEvaluator(
  meta: ConstructorParameters<typeof ScaffoldEvaluator>[0],
  config?: ConstructorParameters<typeof ScaffoldEvaluator>[1]
): ScaffoldEvaluator {
  return new ScaffoldEvaluator(meta, config);
}
